[versions]
kotlin = "2.1.10"

[libraries]
kotlinxSerializationJson = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.8.0"

[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
