name: Generate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "graalvm"
          java-version: "23"
      - uses: gradle/actions/setup-gradle@v4
      - run: |
          ./gradlew :main:run --args="build/main"
          git worktree add generated
          git config --global user.name "intsuc"
          git config --global user.email ""
          cd generated
          rm -rf * .github .gitattributes .gitignore
          mv ../builds/main/build/main/* .
          git add .
          git commit -m "Update"
          git push origin generated
